# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steam/protobufs/steammessages_sitelicenseclient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from steam.protobufs import steammessages_base_pb2 as steam_dot_protobufs_dot_steammessages__base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steam/protobufs/steammessages_sitelicenseclient.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('H\001\200\001\000'),
  serialized_pb=_b('\n5steam/protobufs/steammessages_sitelicenseclient.proto\x1a(steam/protobufs/steammessages_base.proto\"8\n\x12\x43MsgClientSiteInfo\x12\x0f\n\x07site_id\x18\x01 \x01(\x04\x12\x11\n\tsite_name\x18\x02 \x01(\t\".\n\x1d\x43MsgClientSiteLicenseCheckout\x12\r\n\x05\x61ppid\x18\x01 \x01(\r\";\n%CMsgClientSiteLicenseCheckoutResponse\x12\x12\n\x07\x65result\x18\x01 \x01(\x05:\x01\x32\"7\n&CMsgClientSiteLicenseGetAvailableSeats\x12\r\n\x05\x61ppid\x18\x01 \x01(\r\"S\n.CMsgClientSiteLicenseGetAvailableSeatsResponse\x12\x12\n\x07\x65result\x18\x01 \x01(\x05:\x01\x32\x12\r\n\x05seats\x18\x02 \x01(\r\"*\n(CMsgClientSiteLicenseGetContentCacheInfo\"\x83\x01\n0CMsgClientSiteLicenseGetContentCacheInfoResponse\x12\x11\n\tuse_cache\x18\x01 \x01(\x08\x12\x14\n\x0cipv4_address\x18\x02 \x01(\r\x12\x13\n\x0bport_number\x18\x03 \x01(\r\x12\x11\n\tp2p_group\x18\x04 \x01(\rB\x05H\x01\x80\x01\x00')
  ,
  dependencies=[steam_dot_protobufs_dot_steammessages__base__pb2.DESCRIPTOR,])




_CMSGCLIENTSITEINFO = _descriptor.Descriptor(
  name='CMsgClientSiteInfo',
  full_name='CMsgClientSiteInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='site_id', full_name='CMsgClientSiteInfo.site_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='site_name', full_name='CMsgClientSiteInfo.site_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=155,
)


_CMSGCLIENTSITELICENSECHECKOUT = _descriptor.Descriptor(
  name='CMsgClientSiteLicenseCheckout',
  full_name='CMsgClientSiteLicenseCheckout',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid', full_name='CMsgClientSiteLicenseCheckout.appid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=203,
)


_CMSGCLIENTSITELICENSECHECKOUTRESPONSE = _descriptor.Descriptor(
  name='CMsgClientSiteLicenseCheckoutResponse',
  full_name='CMsgClientSiteLicenseCheckoutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eresult', full_name='CMsgClientSiteLicenseCheckoutResponse.eresult', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=264,
)


_CMSGCLIENTSITELICENSEGETAVAILABLESEATS = _descriptor.Descriptor(
  name='CMsgClientSiteLicenseGetAvailableSeats',
  full_name='CMsgClientSiteLicenseGetAvailableSeats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid', full_name='CMsgClientSiteLicenseGetAvailableSeats.appid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=321,
)


_CMSGCLIENTSITELICENSEGETAVAILABLESEATSRESPONSE = _descriptor.Descriptor(
  name='CMsgClientSiteLicenseGetAvailableSeatsResponse',
  full_name='CMsgClientSiteLicenseGetAvailableSeatsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eresult', full_name='CMsgClientSiteLicenseGetAvailableSeatsResponse.eresult', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seats', full_name='CMsgClientSiteLicenseGetAvailableSeatsResponse.seats', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=406,
)


_CMSGCLIENTSITELICENSEGETCONTENTCACHEINFO = _descriptor.Descriptor(
  name='CMsgClientSiteLicenseGetContentCacheInfo',
  full_name='CMsgClientSiteLicenseGetContentCacheInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=450,
)


_CMSGCLIENTSITELICENSEGETCONTENTCACHEINFORESPONSE = _descriptor.Descriptor(
  name='CMsgClientSiteLicenseGetContentCacheInfoResponse',
  full_name='CMsgClientSiteLicenseGetContentCacheInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_cache', full_name='CMsgClientSiteLicenseGetContentCacheInfoResponse.use_cache', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ipv4_address', full_name='CMsgClientSiteLicenseGetContentCacheInfoResponse.ipv4_address', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port_number', full_name='CMsgClientSiteLicenseGetContentCacheInfoResponse.port_number', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='p2p_group', full_name='CMsgClientSiteLicenseGetContentCacheInfoResponse.p2p_group', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=584,
)

DESCRIPTOR.message_types_by_name['CMsgClientSiteInfo'] = _CMSGCLIENTSITEINFO
DESCRIPTOR.message_types_by_name['CMsgClientSiteLicenseCheckout'] = _CMSGCLIENTSITELICENSECHECKOUT
DESCRIPTOR.message_types_by_name['CMsgClientSiteLicenseCheckoutResponse'] = _CMSGCLIENTSITELICENSECHECKOUTRESPONSE
DESCRIPTOR.message_types_by_name['CMsgClientSiteLicenseGetAvailableSeats'] = _CMSGCLIENTSITELICENSEGETAVAILABLESEATS
DESCRIPTOR.message_types_by_name['CMsgClientSiteLicenseGetAvailableSeatsResponse'] = _CMSGCLIENTSITELICENSEGETAVAILABLESEATSRESPONSE
DESCRIPTOR.message_types_by_name['CMsgClientSiteLicenseGetContentCacheInfo'] = _CMSGCLIENTSITELICENSEGETCONTENTCACHEINFO
DESCRIPTOR.message_types_by_name['CMsgClientSiteLicenseGetContentCacheInfoResponse'] = _CMSGCLIENTSITELICENSEGETCONTENTCACHEINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CMsgClientSiteInfo = _reflection.GeneratedProtocolMessageType('CMsgClientSiteInfo', (_message.Message,), dict(
  DESCRIPTOR = _CMSGCLIENTSITEINFO,
  __module__ = 'steam.protobufs.steammessages_sitelicenseclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgClientSiteInfo)
  ))
_sym_db.RegisterMessage(CMsgClientSiteInfo)

CMsgClientSiteLicenseCheckout = _reflection.GeneratedProtocolMessageType('CMsgClientSiteLicenseCheckout', (_message.Message,), dict(
  DESCRIPTOR = _CMSGCLIENTSITELICENSECHECKOUT,
  __module__ = 'steam.protobufs.steammessages_sitelicenseclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseCheckout)
  ))
_sym_db.RegisterMessage(CMsgClientSiteLicenseCheckout)

CMsgClientSiteLicenseCheckoutResponse = _reflection.GeneratedProtocolMessageType('CMsgClientSiteLicenseCheckoutResponse', (_message.Message,), dict(
  DESCRIPTOR = _CMSGCLIENTSITELICENSECHECKOUTRESPONSE,
  __module__ = 'steam.protobufs.steammessages_sitelicenseclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseCheckoutResponse)
  ))
_sym_db.RegisterMessage(CMsgClientSiteLicenseCheckoutResponse)

CMsgClientSiteLicenseGetAvailableSeats = _reflection.GeneratedProtocolMessageType('CMsgClientSiteLicenseGetAvailableSeats', (_message.Message,), dict(
  DESCRIPTOR = _CMSGCLIENTSITELICENSEGETAVAILABLESEATS,
  __module__ = 'steam.protobufs.steammessages_sitelicenseclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseGetAvailableSeats)
  ))
_sym_db.RegisterMessage(CMsgClientSiteLicenseGetAvailableSeats)

CMsgClientSiteLicenseGetAvailableSeatsResponse = _reflection.GeneratedProtocolMessageType('CMsgClientSiteLicenseGetAvailableSeatsResponse', (_message.Message,), dict(
  DESCRIPTOR = _CMSGCLIENTSITELICENSEGETAVAILABLESEATSRESPONSE,
  __module__ = 'steam.protobufs.steammessages_sitelicenseclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseGetAvailableSeatsResponse)
  ))
_sym_db.RegisterMessage(CMsgClientSiteLicenseGetAvailableSeatsResponse)

CMsgClientSiteLicenseGetContentCacheInfo = _reflection.GeneratedProtocolMessageType('CMsgClientSiteLicenseGetContentCacheInfo', (_message.Message,), dict(
  DESCRIPTOR = _CMSGCLIENTSITELICENSEGETCONTENTCACHEINFO,
  __module__ = 'steam.protobufs.steammessages_sitelicenseclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseGetContentCacheInfo)
  ))
_sym_db.RegisterMessage(CMsgClientSiteLicenseGetContentCacheInfo)

CMsgClientSiteLicenseGetContentCacheInfoResponse = _reflection.GeneratedProtocolMessageType('CMsgClientSiteLicenseGetContentCacheInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _CMSGCLIENTSITELICENSEGETCONTENTCACHEINFORESPONSE,
  __module__ = 'steam.protobufs.steammessages_sitelicenseclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseGetContentCacheInfoResponse)
  ))
_sym_db.RegisterMessage(CMsgClientSiteLicenseGetContentCacheInfoResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
