# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steam/protobufs/steammessages_store_steamclient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from steam.protobufs import steammessages_unified_base_steamclient_pb2 as steam_dot_protobufs_dot_steammessages__unified__base__steamclient__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steam/protobufs/steammessages_store_steamclient.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\200\001\001'),
  serialized_pb=_b('\n5steam/protobufs/steammessages_store_steamclient.proto\x1a<steam/protobufs/steammessages_unified_base_steamclient.proto\"J\n&CStore_GetLocalizedNameForTags_Request\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0e\n\x06tagids\x18\x02 \x03(\r\"\x9f\x01\n\'CStore_GetLocalizedNameForTags_Response\x12:\n\x04tags\x18\x01 \x03(\x0b\x32,.CStore_GetLocalizedNameForTags_Response.Tag\x1a\x38\n\x03Tag\x12\r\n\x05tagid\x18\x01 \x01(\r\x12\x14\n\x0c\x65nglish_name\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t2\xc7\x01\n\x05Store\x12\x98\x01\n\x17GetLocalizedNameForTags\x12\'.CStore_GetLocalizedNameForTags_Request\x1a(.CStore_GetLocalizedNameForTags_Response\"*\x82\xb5\x18&Gets tag names in a different language\x1a#\x82\xb5\x18\x1f\x41 service to access store data.B\x03\x80\x01\x01')
  ,
  dependencies=[steam_dot_protobufs_dot_steammessages__unified__base__steamclient__pb2.DESCRIPTOR,])




_CSTORE_GETLOCALIZEDNAMEFORTAGS_REQUEST = _descriptor.Descriptor(
  name='CStore_GetLocalizedNameForTags_Request',
  full_name='CStore_GetLocalizedNameForTags_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='CStore_GetLocalizedNameForTags_Request.language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tagids', full_name='CStore_GetLocalizedNameForTags_Request.tagids', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=193,
)


_CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='CStore_GetLocalizedNameForTags_Response.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tagid', full_name='CStore_GetLocalizedNameForTags_Response.Tag.tagid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='english_name', full_name='CStore_GetLocalizedNameForTags_Response.Tag.english_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='CStore_GetLocalizedNameForTags_Response.Tag.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=355,
)

_CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE = _descriptor.Descriptor(
  name='CStore_GetLocalizedNameForTags_Response',
  full_name='CStore_GetLocalizedNameForTags_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tags', full_name='CStore_GetLocalizedNameForTags_Response.tags', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE_TAG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=355,
)

_CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE_TAG.containing_type = _CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE
_CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE.fields_by_name['tags'].message_type = _CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE_TAG
DESCRIPTOR.message_types_by_name['CStore_GetLocalizedNameForTags_Request'] = _CSTORE_GETLOCALIZEDNAMEFORTAGS_REQUEST
DESCRIPTOR.message_types_by_name['CStore_GetLocalizedNameForTags_Response'] = _CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CStore_GetLocalizedNameForTags_Request = _reflection.GeneratedProtocolMessageType('CStore_GetLocalizedNameForTags_Request', (_message.Message,), dict(
  DESCRIPTOR = _CSTORE_GETLOCALIZEDNAMEFORTAGS_REQUEST,
  __module__ = 'steam.protobufs.steammessages_store_steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CStore_GetLocalizedNameForTags_Request)
  ))
_sym_db.RegisterMessage(CStore_GetLocalizedNameForTags_Request)

CStore_GetLocalizedNameForTags_Response = _reflection.GeneratedProtocolMessageType('CStore_GetLocalizedNameForTags_Response', (_message.Message,), dict(

  Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
    DESCRIPTOR = _CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE_TAG,
    __module__ = 'steam.protobufs.steammessages_store_steamclient_pb2'
    # @@protoc_insertion_point(class_scope:CStore_GetLocalizedNameForTags_Response.Tag)
    ))
  ,
  DESCRIPTOR = _CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE,
  __module__ = 'steam.protobufs.steammessages_store_steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CStore_GetLocalizedNameForTags_Response)
  ))
_sym_db.RegisterMessage(CStore_GetLocalizedNameForTags_Response)
_sym_db.RegisterMessage(CStore_GetLocalizedNameForTags_Response.Tag)


DESCRIPTOR._options = None

_STORE = _descriptor.ServiceDescriptor(
  name='Store',
  full_name='Store',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\202\265\030\037A service to access store data.'),
  serialized_start=358,
  serialized_end=557,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLocalizedNameForTags',
    full_name='Store.GetLocalizedNameForTags',
    index=0,
    containing_service=None,
    input_type=_CSTORE_GETLOCALIZEDNAMEFORTAGS_REQUEST,
    output_type=_CSTORE_GETLOCALIZEDNAMEFORTAGS_RESPONSE,
    serialized_options=_b('\202\265\030&Gets tag names in a different language'),
  ),
])
_sym_db.RegisterServiceDescriptor(_STORE)

DESCRIPTOR.services_by_name['Store'] = _STORE

# @@protoc_insertion_point(module_scope)
