# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steam/protobufs/steammessages_useraccount_steamclient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from steam.protobufs import steammessages_unified_base_steamclient_pb2 as steam_dot_protobufs_dot_steammessages__unified__base__steamclient__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steam/protobufs/steammessages_useraccount_steamclient.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\200\001\001'),
  serialized_pb=_b('\n;steam/protobufs/steammessages_useraccount_steamclient.proto\x1a<steam/protobufs/steammessages_unified_base_steamclient.proto\"+\n)CUserAccount_GetAccountLinkStatus_Request\"Y\n*CUserAccount_GetAccountLinkStatus_Response\x12\x0c\n\x04pwid\x18\x01 \x01(\r\x12\x1d\n\x15identity_verification\x18\x02 \x01(\r\">\n\'CUserAccount_RegisterCompatTool_Request\x12\x13\n\x0b\x63ompat_tool\x18\x01 \x01(\r\"*\n(CUserAccount_RegisterCompatTool_Response2\xea\x02\n\x0bUserAccount\x12\x90\x01\n\x14GetAccountLinkStatus\x12*.CUserAccount_GetAccountLinkStatus_Request\x1a+.CUserAccount_GetAccountLinkStatus_Response\"\x1f\x82\xb5\x18\x1b\x46\x65tches account link status\x12\x98\x01\n\x12RegisterCompatTool\x12(.CUserAccount_RegisterCompatTool_Request\x1a).CUserAccount_RegisterCompatTool_Response\"-\x82\xb5\x18)Register intended account usage of a tool\x1a-\x82\xb5\x18)A service to get user account informationB\x03\x80\x01\x01')
  ,
  dependencies=[steam_dot_protobufs_dot_steammessages__unified__base__steamclient__pb2.DESCRIPTOR,])




_CUSERACCOUNT_GETACCOUNTLINKSTATUS_REQUEST = _descriptor.Descriptor(
  name='CUserAccount_GetAccountLinkStatus_Request',
  full_name='CUserAccount_GetAccountLinkStatus_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=168,
)


_CUSERACCOUNT_GETACCOUNTLINKSTATUS_RESPONSE = _descriptor.Descriptor(
  name='CUserAccount_GetAccountLinkStatus_Response',
  full_name='CUserAccount_GetAccountLinkStatus_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pwid', full_name='CUserAccount_GetAccountLinkStatus_Response.pwid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identity_verification', full_name='CUserAccount_GetAccountLinkStatus_Response.identity_verification', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=259,
)


_CUSERACCOUNT_REGISTERCOMPATTOOL_REQUEST = _descriptor.Descriptor(
  name='CUserAccount_RegisterCompatTool_Request',
  full_name='CUserAccount_RegisterCompatTool_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='compat_tool', full_name='CUserAccount_RegisterCompatTool_Request.compat_tool', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=323,
)


_CUSERACCOUNT_REGISTERCOMPATTOOL_RESPONSE = _descriptor.Descriptor(
  name='CUserAccount_RegisterCompatTool_Response',
  full_name='CUserAccount_RegisterCompatTool_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=367,
)

DESCRIPTOR.message_types_by_name['CUserAccount_GetAccountLinkStatus_Request'] = _CUSERACCOUNT_GETACCOUNTLINKSTATUS_REQUEST
DESCRIPTOR.message_types_by_name['CUserAccount_GetAccountLinkStatus_Response'] = _CUSERACCOUNT_GETACCOUNTLINKSTATUS_RESPONSE
DESCRIPTOR.message_types_by_name['CUserAccount_RegisterCompatTool_Request'] = _CUSERACCOUNT_REGISTERCOMPATTOOL_REQUEST
DESCRIPTOR.message_types_by_name['CUserAccount_RegisterCompatTool_Response'] = _CUSERACCOUNT_REGISTERCOMPATTOOL_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CUserAccount_GetAccountLinkStatus_Request = _reflection.GeneratedProtocolMessageType('CUserAccount_GetAccountLinkStatus_Request', (_message.Message,), dict(
  DESCRIPTOR = _CUSERACCOUNT_GETACCOUNTLINKSTATUS_REQUEST,
  __module__ = 'steam.protobufs.steammessages_useraccount_steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CUserAccount_GetAccountLinkStatus_Request)
  ))
_sym_db.RegisterMessage(CUserAccount_GetAccountLinkStatus_Request)

CUserAccount_GetAccountLinkStatus_Response = _reflection.GeneratedProtocolMessageType('CUserAccount_GetAccountLinkStatus_Response', (_message.Message,), dict(
  DESCRIPTOR = _CUSERACCOUNT_GETACCOUNTLINKSTATUS_RESPONSE,
  __module__ = 'steam.protobufs.steammessages_useraccount_steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CUserAccount_GetAccountLinkStatus_Response)
  ))
_sym_db.RegisterMessage(CUserAccount_GetAccountLinkStatus_Response)

CUserAccount_RegisterCompatTool_Request = _reflection.GeneratedProtocolMessageType('CUserAccount_RegisterCompatTool_Request', (_message.Message,), dict(
  DESCRIPTOR = _CUSERACCOUNT_REGISTERCOMPATTOOL_REQUEST,
  __module__ = 'steam.protobufs.steammessages_useraccount_steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CUserAccount_RegisterCompatTool_Request)
  ))
_sym_db.RegisterMessage(CUserAccount_RegisterCompatTool_Request)

CUserAccount_RegisterCompatTool_Response = _reflection.GeneratedProtocolMessageType('CUserAccount_RegisterCompatTool_Response', (_message.Message,), dict(
  DESCRIPTOR = _CUSERACCOUNT_REGISTERCOMPATTOOL_RESPONSE,
  __module__ = 'steam.protobufs.steammessages_useraccount_steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CUserAccount_RegisterCompatTool_Response)
  ))
_sym_db.RegisterMessage(CUserAccount_RegisterCompatTool_Response)


DESCRIPTOR._options = None

_USERACCOUNT = _descriptor.ServiceDescriptor(
  name='UserAccount',
  full_name='UserAccount',
  file=DESCRIPTOR,
  index=0,
  serialized_options=_b('\202\265\030)A service to get user account information'),
  serialized_start=370,
  serialized_end=732,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAccountLinkStatus',
    full_name='UserAccount.GetAccountLinkStatus',
    index=0,
    containing_service=None,
    input_type=_CUSERACCOUNT_GETACCOUNTLINKSTATUS_REQUEST,
    output_type=_CUSERACCOUNT_GETACCOUNTLINKSTATUS_RESPONSE,
    serialized_options=_b('\202\265\030\033Fetches account link status'),
  ),
  _descriptor.MethodDescriptor(
    name='RegisterCompatTool',
    full_name='UserAccount.RegisterCompatTool',
    index=1,
    containing_service=None,
    input_type=_CUSERACCOUNT_REGISTERCOMPATTOOL_REQUEST,
    output_type=_CUSERACCOUNT_REGISTERCOMPATTOOL_RESPONSE,
    serialized_options=_b('\202\265\030)Register intended account usage of a tool'),
  ),
])
_sym_db.RegisterServiceDescriptor(_USERACCOUNT)

DESCRIPTOR.services_by_name['UserAccount'] = _USERACCOUNT

# @@protoc_insertion_point(module_scope)
